### PR TITLE
Change project/package name

### PR DESCRIPTION
**Pull request by chrisjsewell**
- The GitHub folder has been renamed from  `myst_parser` to `MyST-Parser`
- The package name has been changed from `myst_parser` to `myst-parser`
- Also changed doc references from Myst to MyST

Better sooner rather than later!
@choldgraf this will need to be changed in the MyST-NB setup
@rossbar @mmcky @jstac @akhmerov you are potential users that I can think of that this might affect.

### CODE REVIEW

**Comment by choldgraf** [comment]
Nice - in general this looks good to me, w/ one question:

from the perspective of most filesystems, there is no difference between `MyST-parser` and `myst-parser`, right? Or more to the point, is there value in having us name our repos all-undercased, and then using the camel-casing just for logos/documentation/etc?

I'm trying to see if we are introducing a tiny-but-avoidable annoyance by having camelcase in the git repo name itself...

**Comment by chrisjsewell** [comment]
> is there value in having us name our repos all-undercased, and then using the camel-casing just for logos/documentation/etc?

I only did this because you did 😆 I'm happy with either really, beyond the initial install it's not something users will need to type much. It kinda looks nicer?

**Comment by rossbar** [comment]
Thanks for the heads-up!

**Comment by choldgraf** [comment]
Maybe either @jstac, @mmcky or @rossbar can give their thoughts on `MyST-parser` vs `myst-parser` as an import? I think that in the logo etc it should still be `MyST`...the question is just whether the packages themselves should have camel case

**Comment by jstac** [comment]
I vote CamelCase for the logo and lower case for the import.

**Comment by choldgraf** [comment]
I think I like the idea of:

Camelcase *only* for things like logos, presentations, etc, and lowercase where you'd write "myst" in a `literal_block` or anything related to code.

So we say `myst` or `myst-parser` like this, and **MyST** or **MyST-parser** like this. The second half of the `-` should always be lowercase unless it's an acronym, like **MyST-NB**.

How does that sound?

**Comment by rossbar** [comment]
My vote would be for `myst-parser` as an import. Imagine if you had to type `import NumPy as np` every time...

**Comment by mmcky** [comment]
I have a strong preference for `myst-parser`. It is also inline with PEP8 https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by chrisjsewell** [comment]
Oh yeh definitely `myst-parser` as the import name, which is the case in this PR. I'm too lazy to change the git repo from `MyST-Parser` to `MyST-parser`, so gonna merge.

**Pull request merged**
